name: action demo
on: workflow_dispatch
jobs:
    checkout:
        runs-on: ubuntu-latest
        steps:
            - name: checkout source code
              uses: actions/checkout@v5
            - name: setup JDK
              uses: actions/setup-java@v5
              with:
                distribution: 'temurin'
                java-version: '17'
    
    demo-echo:
        needs: checkout
        runs-on: ubuntu-latest
        steps:
            - name: demo
              run: echo "Testing"