name: filters and activity types
on:
  push:
    branches:
      - 'main'
    paths-ignore:
      - 'README.md'

jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - name: demo trigger for filters
        run: echo "This will trigger on push branch and invalid for readme file"