name: CI Pipeline
on:
  push:
    branches:
      - 'main'
    paths-ignore:
      - 'README.md'
  pull_request:
    types:
      - opened
      - closed
    branches:
      - 'main'
    paths-ignore:
      - 'README.md'
  workflow_dispatch:

jobs:
  JAVA-Build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v5
      - name: setup java 17
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Build maven
        run: mvn clean install
      - name: run test
        run: mvn test
      - name: upload artifact
        uses: actions/upload-artifact@v5
        with:
          name: To-do-jar
          path: target/*.jar
      - name: download artifact
        uses: actions/download-artifact@v5
        with:
          name: To-do-jar
      

