name: Java Maven CI Pipeline

on:
  push:
    branches:
      - 'main'
    paths-ignore:
      - 'README.md'
  pull_request:
    branches:
      - 'main'
    paths-ignore:
      - 'README.md'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  id-token: write
  packages: write   # needed if pushing to GitHub container registry
  pull-requests: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: set-up java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: cache maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: maven-cache-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: maven-cache-${{ runner.os }}-
      - name: Maven Build
        run: |
          mvn clean Install
          tar=$(ls target/*.jar | head -n 1 )
          echo "tar-name=$tar" >> GITHUB_OUTPUT
      - name: Unit Test
        run: mvn test
      - name: Upload Test report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Unit-test-report
          path: target/surefire-reports/**

      


